package com.csye6225.demo.bean;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import javax.persistence.Column;
import javax.persistence.Id;

public class Task {

    //@Id
    //@Column(unique = true)
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private  String id;

    @Column
    private String description;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


}
